export type ProgramIconKey = "pen" | "trend" | "award" | "globe" | "book" | "clip" | "monitor" | "sun";

export interface Program {
  slug: string;
  icon: ProgramIconKey;
  title: string; title_en: string;
  desc: string;  desc_en: string;
  hero: string;  hero_en: string;
  age?: string;  age_en?: string;
  duration?: string;
  schedule?: string;
  badges: string[];   badges_en: string[];
  about: string[];    about_en: string[];
  subjects: { name: string; icon: string }[];
  subjects_en: { name: string; icon: string }[];
  features: { title: string; desc: string }[];
  features_en: { title: string; desc: string }[];
  targets: string[];
  targets_en: string[];
}

export const programs: Program[] = [
  {
    slug: "ibtidai-sinif",
    icon: "pen",
    title: "İbtidai sinif (1–4)",
    title_en: "Primary School (1–4)",
    desc: "Dünyagörüşün artırılması, məntiqi təfəkkürün inkişafı və məktəb dərslərinin mənimsənilməsi.",
    desc_en: "Expanding worldview, developing logical thinking and mastering school lessons.",
    hero: "Möhkəm bilik, güclü baza.",
    hero_en: "Strong knowledge, solid foundation.",
    age: "1–4 sinif",
    age_en: "Grades 1–4",
    duration: "9 ay (sentyabr–may)",
    schedule: "Həftədə 3 gün · 60 dəq",
    badges: ["Oyunla öyrənmə", "Kiçik qruplar"],
    badges_en: ["Learning through play", "Small groups"],
    about: [
      "MQ Akademiyasının ibtidai sinif proqramı uşaqları yalnız dərs üçün deyil, həyat üçün hazırlayır. Müasir pedaqoji metodlarla hər uşağın fərdi inkişaf tempi nəzərə alınır.",
      "Məntiqi düşüncə, kreativ yanaşma və sosial bacarıqlar — bunlar akademik biliklərlə paralel inkişaf etdirilir.",
    ],
    about_en: [
      "MQ Academy's primary school program prepares children not just for lessons, but for life. Each child's individual development pace is taken into account using modern pedagogical methods.",
      "Logical thinking, creative approach and social skills — these are developed in parallel with academic knowledge.",
    ],
    subjects: [
      { name: "Azərbaycan dili", icon: "📝" },
      { name: "Riyaziyyat", icon: "🔢" },
      { name: "Həyat bilgisi", icon: "🌍" },
      { name: "İngilis dili", icon: "🌐" },
      { name: "Oxu", icon: "📖" },
      { name: "Məntiqi düşüncə", icon: "🧩" },
      { name: "Təsviri incəsənət", icon: "🎨" },
      { name: "Texnologiya", icon: "🛠️" },
    ],
    subjects_en: [
      { name: "Azerbaijani Language", icon: "📝" },
      { name: "Mathematics", icon: "🔢" },
      { name: "Life Studies", icon: "🌍" },
      { name: "English Language", icon: "🌐" },
      { name: "Reading", icon: "📖" },
      { name: "Logical Thinking", icon: "🧩" },
      { name: "Visual Arts", icon: "🎨" },
      { name: "Technology", icon: "🛠️" },
    ],
    features: [
      { title: "Fərdi yanaşma", desc: "Hər uşağın inkişaf tempinə uyğun tədris planı hazırlanır." },
      { title: "Oyunla öyrənmə", desc: "Dərslər interaktiv, əyləncəli metodlarla keçirilir." },
      { title: "Kiçik qruplar", desc: "Maksimum 8 nəfərlik qruplar — hər uşağa diqqət." },
      { title: "Valideyn əlaqəsi", desc: "Aylıq hesabat və valideynlərlə daimi ünsiyyət." },
    ],
    features_en: [
      { title: "Individual approach", desc: "A teaching plan tailored to each child's development pace." },
      { title: "Learning through play", desc: "Lessons are conducted with interactive, fun methods." },
      { title: "Small groups", desc: "Maximum 8 students per group — attention for every child." },
      { title: "Parent communication", desc: "Monthly reports and ongoing communication with parents." },
    ],
    targets: [
      "Dərs materiallarını dərindən mənimsəyir, müstəqil işləmə bacarığı qazanır",
      "Məntiqi tapşırıqları həll edir",
      "Özünü cəmiyyətdə rahat hiss edir",
    ],
    targets_en: [
      "Deeply grasps school subjects and gains independent study skills",
      "Solves logical tasks",
      "Feels comfortable in social settings",
    ],
  },
  {
    slug: "tekmillesdirme",
    icon: "trend",
    title: "Təkmilləşdirmə (5–8)",
    title_en: "Improvement (5–8)",
    desc: "Məktəb proqramının dərindən öyrənilməsi, zəif fənlərin gücləndirilməsi və baza biliklərin formalaşdırılması.",
    desc_en: "In-depth study of the school curriculum, strengthening weak subjects and building foundational knowledge.",
    hero: "Hər fəndə möhkəm bilik — uğurlu gələcəyin təməli.",
    hero_en: "Solid knowledge in every subject — the foundation of a successful future.",
    age: "5–8 sinif",
    age_en: "Grades 5–8",
    duration: "9 ay (sentyabr–may)",
    schedule: "Həftədə 2–3 gün · 90 dəq",
    badges: ["Fərdi proqram", "Bütün fənlər"],
    badges_en: ["Individual program", "All subjects"],
    about: [
      "5–8-ci sinif şagirdləri üçün hazırlanmış bu proqram məktəb kurikulumunu dərinləşdirir. Hər şagirdin zəif olduğu fənlər aşkar edilir və xüsusi diqqət göstərilir.",
      "Güclü baza biliklər olmadan yuxarı siniflərdə uğur mümkün deyil. Biz bu əsası birlikdə qururuq — səbrlə, ardıcıllıqla, nəticə istiqamətli.",
    ],
    about_en: [
      "This program, designed for grades 5–8, deepens the school curriculum. Each student's weak subjects are identified and given special attention.",
      "Success in higher grades is not possible without strong foundational knowledge. We build this foundation together — patiently, consistently, and result-oriented.",
    ],
    subjects: [
      { name: "Riyaziyyat", icon: "📐" },
      { name: "Fizika", icon: "⚡" },
      { name: "Kimya", icon: "🧪" },
      { name: "Azərbaycan dili", icon: "📝" },
      { name: "İngilis dili", icon: "🌐" },
      { name: "Rus dili", icon: "🇷🇺" },
      { name: "Biologiya", icon: "🌿" },
      { name: "Coğrafiya", icon: "🗺️" },
      { name: "Tarix", icon: "🏛️" },
    ],
    subjects_en: [
      { name: "Mathematics", icon: "📐" },
      { name: "Physics", icon: "⚡" },
      { name: "Chemistry", icon: "🧪" },
      { name: "Azerbaijani Language", icon: "📝" },
      { name: "English Language", icon: "🌐" },
      { name: "Russian Language", icon: "🇷🇺" },
      { name: "Biology", icon: "🌿" },
      { name: "Geography", icon: "🗺️" },
      { name: "History", icon: "🏛️" },
    ],
    features: [
      { title: "Diaqnostik qiymətləndirmə", desc: "İlk həftədə hər şagirdin səviyyəsi müəyyən edilir." },
      { title: "Fərdi plan", desc: "Hər şagird üçün ayrıca tədris cədvəli hazırlanır." },
      { title: "Həftəlik izləmə", desc: "Müntəzəm testlər və ev tapşırıqlarının yoxlanması." },
      { title: "Çalışma bazası", desc: "Geniş sual bankı və məktəb imtahan materialları." },
    ],
    features_en: [
      { title: "Diagnostic assessment", desc: "Each student's level is determined in the first week." },
      { title: "Individual plan", desc: "A separate study schedule is prepared for each student." },
      { title: "Weekly monitoring", desc: "Regular tests and checking of homework assignments." },
      { title: "Practice bank", desc: "Extensive question bank and school exam materials." },
    ],
    targets: [
      "Məktəb qiymətlərini yüksəldir",
      "Fənni sevir və maraqla öyrənir",
      "Abituriyent hazırlığına möhkəm baza ilə gedir",
      "Özgüvəni artan şagird olur",
    ],
    targets_en: [
      "Improves school grades",
      "Develops a love and interest for subjects",
      "Enters university prep with a solid foundation",
      "Becomes a more self-confident student",
    ],
  },
  {
    slug: "abituriyent",
    icon: "award",
    title: "Abituriyent (9–11)",
    title_en: "University Prep (9–11)",
    desc: "Dövlət İmtahan Mərkəzinin (DİM) proqramına tam uyğun, yüksək nəticə hədəfli universitetə qəbul hazırlığı.",
    desc_en: "University admission preparation fully aligned with the State Examination Centre (DIM) program, targeting high results.",
    hero: "DİM-ə hazırlan, arzuladığın universiteti qazan.",
    hero_en: "Prepare for DIM, win your dream university.",
    age: "9–11 sinif",
    age_en: "Grades 9–11",
    duration: "1–2 il",
    schedule: "Həftədə 4–5 gün · 90 dəq",
    badges: ["DİM proqramı", "Yüksək nəticə", "Hər qrup fənni"],
    badges_en: ["DIM program", "High results", "All subject groups"],
    about: [
      "MQ Akademiyasının abituriyent proqramı DİM-in rəsmi imtahan formatına tam uyğun hazırlanmışdır. Hər fənn üzrə ixtisaslaşmış müəllimlər şagirdlərə real imtahan şəraitini yaşatmağa kömək edir.",
      "İl ərzində keçirilən sınaq imtahanları, zamanla artırılan çətinlik dərəcəsi və intensiv çalışma — bunlar yüksək bala aparan yoldur. Hər şagirdin hədəfi müəyyən edilir və o hədəfə birlikdə çatılır.",
    ],
    about_en: [
      "MQ Academy's university prep program is fully aligned with the official DIM exam format. Specialist teachers in each subject help students experience real exam conditions.",
      "Practice exams held throughout the year, gradually increasing difficulty levels and intensive study — these are the path to a high score. Each student's goal is identified and reached together.",
    ],
    subjects: [
      { name: "Riyaziyyat", icon: "📐" },
      { name: "Fizika", icon: "⚡" },
      { name: "Kimya", icon: "🧪" },
      { name: "Biologiya", icon: "🌿" },
      { name: "Coğrafiya", icon: "🗺️" },
      { name: "Tarix", icon: "🏛️" },
      { name: "Azərbaycan dili", icon: "📝" },
      { name: "Ədəbiyyat", icon: "📚" },
      { name: "İngilis dili", icon: "🌐" },
      { name: "İnformatika", icon: "💻" },
    ],
    subjects_en: [
      { name: "Mathematics", icon: "📐" },
      { name: "Physics", icon: "⚡" },
      { name: "Chemistry", icon: "🧪" },
      { name: "Biology", icon: "🌿" },
      { name: "Geography", icon: "🗺️" },
      { name: "History", icon: "🏛️" },
      { name: "Azerbaijani Language", icon: "📝" },
      { name: "Literature", icon: "📚" },
      { name: "English Language", icon: "🌐" },
      { name: "Informatics", icon: "💻" },
    ],
    features: [
      { title: "Sınaq imtahanları", desc: "Ayda 1–2 dəfə real DİM şəraitini simulyasiya edən imtahanlar." },
      { title: "Sual analizi", desc: "Keçmiş illərin bütün DİM sualları sistemli şəkildə işlənir." },
      { title: "Zaman idarəetməsi", desc: "Sürət və dəqiqliyi artırmaq üçün xüsusi texnikalar." },
      { title: "Motivasiya dəstəyi", desc: "Psixoloji hazırlıq, stress idarəetməsi və motivasiya sessiyaları." },
    ],
    features_en: [
      { title: "Practice exams", desc: "1–2 exams per month simulating real DIM conditions." },
      { title: "Question analysis", desc: "All past DIM questions are systematically worked through." },
      { title: "Time management", desc: "Special techniques to improve speed and accuracy." },
      { title: "Motivation support", desc: "Psychological preparation, stress management and motivation sessions." },
    ],
    targets: [
      "Yüksək DİM balı toplayır",
      "Seçdiyi ixtisasa qəbul olur",
      "İmtahan psixologiyasına hazırdır",
      "Vaxtı effektiv idarə edir",
    ],
    targets_en: [
      "Achieves a high DIM score",
      "Gets accepted to their chosen major",
      "Prepared for exam psychology",
      "Manages time effectively",
    ],
  },
  {
    slug: "xarici-dil",
    icon: "globe",
    title: "Xarici dil",
    title_en: "Foreign Language",
    desc: "Danışıq, yazı və dinləmə bacarıqlarının inkişafı. General English və IELTS hazırlığı.",
    desc_en: "Developing speaking, writing and listening skills. General English and IELTS preparation.",
    hero: "İngilis dilini öyrən — dünyaya açıl.",
    hero_en: "Learn English — open the world.",
    age: "Hər yaş",
    age_en: "All ages",
    duration: "6–12 ay (səviyyəyə görə)",
    schedule: "Həftədə 3 gün · 90 dəq",
    badges: ["General English", "IELTS", "Hər səviyyə"],
    badges_en: ["General English", "IELTS", "All levels"],
    about: [
      "Başlanğıcdan C1 səviyyəsinə, General English-dən IELTS hazırlığına — MQ Akademiyasında bütün dil ehtiyaclarınız qarşılanır. Dərslərimiz kommunikativ metodoloji əsasında qurulub.",
      "Real həyat situasiyaları, autentik materiallar və intensiv danışıq məşqləri ilə tələbələrimiz qısa müddətdə dil baryerini aşır. IELTS hazırlığı üçün isə xüsusi bal strategiyaları tədris edilir.",
    ],
    about_en: [
      "From beginner to C1 level, from General English to IELTS preparation — all your language needs are met at MQ Academy. Our lessons are built on a communicative methodology.",
      "With real-life situations, authentic materials and intensive speaking practice, our students overcome the language barrier quickly. Special score strategies are also taught for IELTS preparation.",
    ],
    subjects: [
      { name: "Speaking", icon: "🗣️" },
      { name: "Listening", icon: "👂" },
      { name: "Reading", icon: "📖" },
      { name: "Writing", icon: "✍️" },
      { name: "Grammar", icon: "📚" },
      { name: "IELTS Hazırlığı", icon: "🎯" },
    ],
    subjects_en: [
      { name: "Speaking", icon: "🗣️" },
      { name: "Listening", icon: "👂" },
      { name: "Reading", icon: "📖" },
      { name: "Writing", icon: "✍️" },
      { name: "Grammar", icon: "📚" },
      { name: "IELTS Preparation", icon: "🎯" },
    ],
    features: [
      { title: "Kommunikativ metod", desc: "Dərsin 60%-i canlı danışıq və müzakirə üzərinde qurulub." },
      { title: "Autentik materiallar", desc: "BBC, TED Talks, Guardian və digər real mənbələrdən materiallar." },
      { title: "IELTS strategiyaları", desc: "Hər tapşırıq tipi üçün xüsusi yanaşma və nümunə cavablar." },
      { title: "Səviyyə testləri", desc: "Hər 6 həftədən bir rəsmi inkişaf testi keçirilir." },
    ],
    features_en: [
      { title: "Communicative method", desc: "60% of the lesson is built on live speaking and discussion." },
      { title: "Authentic materials", desc: "Materials from BBC, TED Talks, Guardian and other real sources." },
      { title: "IELTS strategies", desc: "Special approaches and sample answers for each task type." },
      { title: "Level tests", desc: "An official progress test is held every 6 weeks." },
    ],
    targets: [
      "Sərbəst ünsiyyət qura bilir",
      "IELTS-də hədəf bandı alır",
      "Yazılı ingilis dili bacarığı güclənir",
      "Dil öyrənməyə müsbət münasibət yaranır",
    ],
    targets_en: [
      "Can communicate freely",
      "Achieves target band score in IELTS",
      "Written English skills are strengthened",
      "Develops a positive attitude towards language learning",
    ],
  },
  {
    slug: "magistr",
    icon: "book",
    title: "Magistr hazırlığı",
    title_en: "Master's Degree Preparation",
    desc: "Universitet məzunlarının magistratura pilləsinə peşəkar səviyyədə hazırlığı.",
    desc_en: "Professional-level preparation of university graduates for the master's degree stage.",
    hero: "Karyeranın növbəti mərhələsi — magistratura.",
    hero_en: "The next stage of your career — master's degree.",
    age: "Bakalavr məzunları",
    age_en: "Bachelor's graduates",
    duration: "6–9 ay",
    schedule: "Həftədə 3–4 gün · 90 dəq",
    badges: ["Magistratura", "Peşəkar hazırlıq", "Bütün ixtisaslar"],
    badges_en: ["Master's degree", "Professional preparation", "All majors"],
    about: [
      "Magistratura imtahanı ciddi hazırlıq tələb edir. MQ Akademiyası bu prosesdə sizə tam dəstək verir — imtahan formatından tutmuş mövzuların dərindən işlənməsinə qədər.",
      "Xüsusi fənn biliklərini, imtahan strategiyalarını və zaman idarəetməsini birlikdə məşq edəcəyik. Məzunlarımız hər il uğurla magistraturaya qəbul olunur.",
    ],
    about_en: [
      "The master's exam requires serious preparation. MQ Academy provides you with full support throughout this process — from the exam format to the in-depth study of topics.",
      "We will practise specialist subject knowledge, exam strategies and time management together. Our graduates are successfully admitted to master's programs every year.",
    ],
    subjects: [
      { name: "İxtisas fənni", icon: "🎓" },
      { name: "Xarici dil", icon: "🌐" },
      { name: "Ümumi bilik", icon: "🧠" },
      { name: "Test strategiyası", icon: "📋" },
    ],
    subjects_en: [
      { name: "Specialist subject", icon: "🎓" },
      { name: "Foreign language", icon: "🌐" },
      { name: "General knowledge", icon: "🧠" },
      { name: "Test strategy", icon: "📋" },
    ],
    features: [
      { title: "İmtahan analizi", desc: "Əvvəlki illərin magistr imtahan sualları ətraflı işlənir." },
      { title: "Fərdi yanaşma", desc: "Hər tələbənin zəif tərəfləri müəyyənləşdirilir və fərdi plan qurulur." },
      { title: "Sınaq imtahanları", desc: "Real imtahan şəraitini simulyasiya edən məşq imtahanları." },
      { title: "Nəticəyə zəmanət", desc: "Hər tələbənin imtahan balı müntəzəm izlənilir və hədəfə çatmaq üçün plan tənzimlənir." },
    ],
    features_en: [
      { title: "Exam analysis", desc: "Previous years' master's exam questions are thoroughly worked through." },
      { title: "Individual approach", desc: "Each student's weak areas are identified and an individual plan is built." },
      { title: "Practice exams", desc: "Practice exams simulating real exam conditions." },
      { title: "Result guarantee", desc: "Each student's exam score is regularly tracked and the plan is adjusted to reach the target." },
    ],
    targets: [
      "Magistratura imtahanında yüksək bal alır",
      "Arzuladığı universitetə qəbul olur",
    ],
    targets_en: [
      "Achieves a high score in the master's exam",
      "Gets accepted to their desired university",
    ],
  },
  {
    slug: "miq",
    icon: "clip",
    title: "MİQ — Müəllimlərin İmtahanı",
    title_en: "MIQ — Teachers' Exam",
    desc: "Müəllimlərin işə qəbul imtahanlarına peşəkar səviyyədə hazırlığı.",
    desc_en: "Professional-level preparation for teachers' employment exams.",
    hero: "MİQ-i keç, peşəkar müəllim kimi çalış.",
    hero_en: "Pass MIQ, work as a professional teacher.",
    age: "Pedaqoji ixtisas sahibləri",
    age_en: "Holders of a pedagogical qualification",
    duration: "4–6 ay",
    schedule: "Həftədə 3 gün · 90 dəq",
    badges: ["MİQ formatı", "Pedaqogika", "Fənn bilikləri"],
    badges_en: ["MIQ format", "Pedagogy", "Subject knowledge"],
    about: [
      "MİQ imtahanı müəllimlik sertifikatı almaq istəyən hər kəs üçün vacib bir addımdır. MQ Akademiyasında bu imtahana sistematik və məqsədyönlü hazırlıq təmin edilir.",
      "Hər mövzu aydın izah, strukturlu təkrar və praktiki məşqlərlə möhkəmləndirilir. Müəllimlərimiz sizi imtahana deyil, uğura hazırlayır.",
    ],
    about_en: [
      "The MIQ exam is an important step for anyone who wants to obtain a teaching certificate. MQ Academy provides systematic and goal-oriented preparation for this exam.",
      "Each topic is reinforced with clear explanations, structured revision and practical exercises. Our teachers prepare you not just for the exam, but for success.",
    ],
    subjects: [
      { name: "İxtisas fənni", icon: "📚" },
      { name: "Test strategiyası", icon: "📋" },
      { name: "Müsahibə mərhələsi", icon: "🗣️" },
      { name: "Kurikulum", icon: "📋" },
    ],
    subjects_en: [
      { name: "Specialist subject", icon: "📚" },
      { name: "Test strategy", icon: "📋" },
      { name: "Interview stage", icon: "🗣️" },
      { name: "Curriculum", icon: "📋" },
    ],
    features: [
      { title: "MİQ formatına tam uyğun", desc: "Rəsmi imtahan strukturuna görə qurulmuş tədris planı." },
      { title: "Sual analizi", desc: "Son illərin bütün MİQ sualları sistemli şəkildə işlənir." },
      { title: "Pedaqoji biliklər", desc: "Müasir tədris metodları, sinif idarəetməsi, qiymətləndirmə." },
      { title: "Güclü dəstək", desc: "Hər həftə mini test və nəticə analizi." },
    ],
    features_en: [
      { title: "Fully aligned with MIQ format", desc: "Teaching plan built according to the official exam structure." },
      { title: "Question analysis", desc: "All MIQ questions from recent years are systematically worked through." },
      { title: "Pedagogical knowledge", desc: "Modern teaching methods, classroom management, assessment." },
      { title: "Strong support", desc: "Mini test and result analysis every week." },
    ],
    targets: [
      "MİQ imtahanından uğurla keçir",
      "Müasir pedaqoji bilikləri mənimsəyir",
    ],
    targets_en: [
      "Successfully passes the MIQ exam",
      "Masters modern pedagogical knowledge",
    ],
  },
  {
    slug: "ofis-proqramlari",
    icon: "monitor",
    title: "Ofis proqramları",
    title_en: "Office Programs",
    desc: "Karyerada uğur qazanmaq üçün zəruri kompüter proqramlarının sıfırdan öyrənilməsi.",
    desc_en: "Learning essential computer programs from scratch for career success.",
    hero: "Kompüter bacarıqları — müasir iş dünyasının açarı.",
    hero_en: "Computer skills — the key to the modern work world.",
    age: "Hər yaş",
    age_en: "All ages",
    duration: "3–6 ay",
    schedule: "Həftədə 3 gün · 90 dəq",
    badges: ["Microsoft Office", "Sıfırdan", "Sertifikat"],
    badges_en: ["Microsoft Office", "From scratch", "Certificate"],
    about: [
      "Müasir iş mühitində kompüter bacarıqları əsas tələb halına gəlib. MQ Akademiyasında Microsoft Office paketini sıfırdan öyrənib peşəkar səviyyəyə çata bilərsiniz.",
      "Praktiki tapşırıqlar, real iş ssenarilərinin simulyasiyası və addım-addım öyrədim metodu ilə qısa müddətdə iş proseslərini daha sürətli, dəqiq və effektiv yerinə yetirəcəksiniz.",
    ],
    about_en: [
      "Computer skills have become a fundamental requirement in the modern work environment. At MQ Academy, you can learn the Microsoft Office suite from scratch and reach a professional level.",
      "With practical tasks, simulation of real work scenarios and a step-by-step teaching method, you will carry out work processes faster, more accurately and more effectively in a short time.",
    ],
    subjects: [
      { name: "Microsoft Word", icon: "📄" },
      { name: "Microsoft Excel", icon: "📊" },
      { name: "Microsoft PowerPoint", icon: "📽️" },
      { name: "Microsoft Outlook", icon: "📧" },
      { name: "İlkin biliklər", icon: "💻" },
    ],
    subjects_en: [
      { name: "Microsoft Word", icon: "📄" },
      { name: "Microsoft Excel", icon: "📊" },
      { name: "Microsoft PowerPoint", icon: "📽️" },
      { name: "Microsoft Outlook", icon: "📧" },
      { name: "Basic skills", icon: "💻" },
    ],
    features: [
      { title: "Sıfırdan başlayır", desc: "Heç bir ön bilik tələb olunmur, tamamilə əsasdan öyrənilir." },
      { title: "Praktik yönümlü", desc: "Hər dərsdə real iş tapşırıqları yerinə yetirilir." },
      { title: "Rəsmi sertifikat", desc: "Kursu bitirən tələbələrə MQ Akademiyasının rəsmi sertifikatı verilir." },
      { title: "Kiçik qruplar", desc: "Maksimum 6 nəfərlik qrupda fərdi diqqət." },
    ],
    features_en: [
      { title: "Starts from scratch", desc: "No prior knowledge required, learned completely from the basics." },
      { title: "Practice-oriented", desc: "Real work tasks are completed in every lesson." },
      { title: "Official certificate", desc: "Students who complete the course receive MQ Academy's official certificate." },
      { title: "Small groups", desc: "Individual attention in a group of maximum 6 people." },
    ],
    targets: [
      "Excel-də cədvəl və hesabat hazırlayır",
      "Word-də peşəkar sənəd tərtib edir",
      "PowerPoint ilə təqdimat hazırlayır",
      "İş müraciətlərində kompüter bilikləri tələbini ödəyir",
    ],
    targets_en: [
      "Prepares spreadsheets and reports in Excel",
      "Composes professional documents in Word",
      "Prepares presentations with PowerPoint",
      "Meets computer knowledge requirements in job applications",
    ],
  },
  {
    slug: "yay-mektepleri",
    icon: "sun",
    title: "Yay məktəbləri",
    title_en: "Summer Schools",
    desc: "Şagirdlərin yay tətilini həm əyləncəli, həm də intellektual keçirmələri üçün xüsusi inkişaf proqramları.",
    desc_en: "Special development programs for students to spend the summer holidays both enjoyably and intellectually.",
    hero: "Yayı boş keçirmə — inkişaf et, əylən, tanış ol.",
    hero_en: "Don't waste the summer — develop, have fun, make friends.",
    age: "6–16 yaş",
    age_en: "Ages 6–16",
    duration: "4–8 həftə (iyun–avqust)",
    schedule: "Həftə içi · Hər gün · 4 saat",
    badges: ["Yay tətili", "Əyləncə + Bilik"],
    badges_en: ["Summer holiday", "Fun + Knowledge"],
    about: [
      "MQ Akademiyasının yay məktəbi şagirdlərə tətili boş keçirməmək üçün ən yaxşı fürsəti verir. Bilik, əylənc və yeni dostlar — hamısı bir yerdə.",
      "Hər yaş qrupu üçün fərqli proqramlar hazırlanmışdır. Sabah dərsləri akademik mövzuları, günorta fəaliyyətlər isə kreativ, idman və komanda oyunlarını əhatə edir.",
    ],
    about_en: [
      "MQ Academy's summer school gives students the best opportunity not to waste the holiday. Knowledge, fun and new friends — all in one place.",
      "Different programs have been prepared for each age group. Morning lessons cover academic topics, while afternoon activities include creative, sports and team games.",
    ],
    subjects: [
      { name: "Riyaziyyat", icon: "📐" },
      { name: "İngilis dili", icon: "🌐" },
      { name: "Yaradıcı yazı", icon: "✍️" },
      { name: "Məntiqi oyunlar", icon: "🧩" },
    ],
    subjects_en: [
      { name: "Mathematics", icon: "📐" },
      { name: "English Language", icon: "🌐" },
      { name: "Creative writing", icon: "✍️" },
      { name: "Logic games", icon: "🧩" },
    ],
    features: [
      { title: "Komanda ruhu", desc: "Qrup fəaliyyətləri ilə sosial bacarıqlar inkişaf edir." },
      { title: "Fərqli proqramlar", desc: "Hər yaş qrupu üçün ayrıca hazırlanmış fəaliyyət planı." },
      { title: "Güvənli mühit", desc: "Nəzarətli, sağlam və stimullaşdırıcı öyrənmə mühiti." },
      { title: "Həftəlik hesabat", desc: "Valideynlərə həftəlik inkişaf xülasəsi göndərilir." },
    ],
    features_en: [
      { title: "Team spirit", desc: "Social skills develop through group activities." },
      { title: "Different programs", desc: "A separately prepared activity plan for each age group." },
      { title: "Safe environment", desc: "A supervised, healthy and stimulating learning environment." },
      { title: "Weekly report", desc: "A weekly development summary is sent to parents." },
    ],
    targets: [
      "Tətili məhsuldar keçirir",
      "Yeni dostlar qazanır",
      "Akademik bilikləri möhkəmlədir",
      "Yaradıcı düşüncəsini inkişaf etdirir",
    ],
    targets_en: [
      "Spends the holiday productively",
      "Makes new friends",
      "Consolidates academic knowledge",
      "Develops creative thinking",
    ],
  },
];

export function getProgramBySlug(slug: string): Program | undefined {
  return programs.find((p) => p.slug === slug);
}
